<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Сайты</h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="urls">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Имя</th>
                        <th>Последняя проверка</th>
                        <th>Код ответа</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (isset($urlsCheckData)): ?>
                        <?php foreach ($urlsCheckData as $url): ?>
                            <tr>
                                <td>
                                    <?= $url['id'] ?>
                                </td>
                                <td>
                                    <a href="<?= $router->urlFor('urls.show', ['id' => $url['id']]) ?>">
                                        <?= $url['name'] ?>
                                    </a>
                                </td>
                                <td>
                                    <?= $url['createdAt'] ?>
                                </td>
                                <td>
                                    <?= $url['statusCode'] ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif ?>
                </tbody>
            </table>
        </div>
    </div>
</main>