<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Сайт: <?= $url->getName() ?></h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                    <tr>
                        <td>ID</td>
                        <td><?= $url->getId() ?></td>
                    </tr>
                    <tr>
                        <td>Имя</td>
                        <td><?= $url->getName() ?></td>
                    </tr>
                    <tr>
                        <td>Дата создания</td>
                        <td><?= $url->getDate() ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <h2 class="mt-5 mb-3">Проверки</h2>
        <form action="<?= $router->urlFor('urls.check', ['url_id' => $url->getId()]) ?>" class="mb-3" method="post">
            <input type="submit" class="btn btn-primary" value="Запустить проверку">
        </form>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-wrap" data-test="checks">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Код ответа</th>
                        <th style="min-width: 170px;">h1</th>
                        <th style="min-width: 200px;">title</th>
                        <th style="min-width: 260px;">description</th>
                        <th style="min-width: 100px;">Дата создания</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($checkData as $check) : ?>
                        <tr>
                            <td><?= $check->getId() ?></td>
                            <td><?= $check->getStatusCode() ?></td>
                            <td class="text-break">
                                <?= $check->getH1() ?>
                            </td>
                            <td class="text-break">
                                <?= $check->getTitle() ?>
                            </td>
                            <td class="text-break">
                                <?= $check->getDescription() ?>
                            </td>
                            <td><?= $check->getCheckDate() ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</main>