<main class="flex-grow-1">
    <div class="container-xl mt-3">
        <div class="row">
            <div class="col-md-10 col-lg-8 col-12 mx-auto border rounded-3 bg-light p-sm-5 p-4">
                <h1 class="display-3">Анализатор страниц</h1>
                <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
                <form action="<?= $router->urlFor('urls.store') ?>" method="post" class="d-flex flex-wrap column-gap-4 row-gap-2" required="">
                    <div class="flex-grow-1">
                        <label for="text" class="visually-hidden">Url для проверки</label>
                        <input type="text" name="url[name]" value="<?= htmlspecialchars($url['name']) ?>" class="form-control form-control-lg <?= !empty($errors) ? 'is-invalid' : '' ?>" placeholder="https://www.example.com">
                        <?php if (isset($errors['name'])): ?>
                            <div class="invalid-feedback">
                                <?= $errors['name'][0] ?>
                            </div>
                        <?php endif ?>
                    </div>
                    <div class="">
                        <input type="submit" class="btn btn-primary btn-lg px-5 text-uppercase" value="Проверить">
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>