<?= $this->fetch('header.phtml') ?>

<?= $this->fetch('alerts.phtml', ['flash' => $flash]) ?>

<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Сайт: <?= $url->getName() ?></h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                    <tr>
                        <td>ID</td>
                        <td><?= $url->getId() ?></td>
                    </tr>
                    <tr>
                        <td>Имя</td>
                        <td><?= $url->getName() ?></td>
                    </tr>
                    <tr>
                        <td>Дата создания</td>
                        <td><?= $url->getDate() ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <h2 class="mt-5 mb-3">Проверки</h2>
        <form class="mb-3" method="post" action="<?= $router->urlFor('urls.check', ['url_id' => $url->getId()]) ?>">
            <input type="submit" class="btn btn-primary" value="Запустить проверку">
        </form>
        <table class="table table-bordered table-hover" data-test="checks">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Код ответа</th>
                    <th>h1</th>
                    <th>title</th>
                    <th>description</th>
                    <th>Дата создания</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($checkData as $check) : ?>
                    <tr>
                        <td><?= $check['id'] ?></td>
                        <td><?= $check['status_code'] ?></td>
                        <td class="text-break"><?= $check['h1'] ?></td>
                        <td class="text-break"><?= $check['title'] ?></td>
                        <td class="text-break"><?= $check['description'] ?></td>
                        <td><?= $check['created_at'] ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</main>

<?= $this->fetch('footer.phtml') ?>